// Digital-Nurture-PythonFSE-main/Digital-Nurture-PythonFSE-main/Python FSE/Deepskilling/Module2_FrontendDev/FrontEnd Hands-on/handson_07/src/app/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  @Input() siteName: string = 'Student Portal';
}

<header class="site-header">
    <div class="logo">
        <a routerLink="/" style="text-decoration: none; color: white;">
            <span>{{ siteName }}</span>
        </a>
    </div>
    <nav class="nav-menu">
        <ul>
            <li><a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Courses</a></li>
            <li><a routerLink="/profile" routerLinkActive="active">Profile</a></li>
        </ul>
    </nav>
</header>

// Digital-Nurture-PythonFSE-main/Digital-Nurture-PythonFSE-main/Python FSE/Deepskilling/Module2_FrontendDev/FrontEnd Hands-on/handson_06/src/components/Header.jsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useSelector } from 'react-redux';

export default function Header({ siteName = "Student Portal" }) {
    const enrolledCourses = useSelector(state => state.enrollment.enrolledCourses);
    const location = useLocation();

    return (
        <header className="site-header">
            <div className="logo">
                <Link to="/" style={{ textDecoration: 'none', color: '#ffffff' }}>
                    <span>{siteName}</span>
                </Link>
            </div>
            <nav className="nav-menu">
                <ul>
                    <li>
                        <Link to="/" className={location.pathname === '/' ? 'active' : ''}>Home</Link>
                    </li>
                    <li>
                        <Link to="/courses" className={location.pathname.startsWith('/courses') ? 'active' : ''}>Courses</Link>
                    </li>
                    <li>
                        <Link to="/profile" className={location.pathname === '/profile' ? 'active' : ''}>Profile</Link>
                    </li>
                </ul>
            </nav>
            <div className="enrollment-badge">
                Enrolled: <span className="badge-count">{enrolledCourses.length}</span>
            </div>
        </header>
    );
}
