// Digital-Nurture-PythonFSE-main/Digital-Nurture-PythonFSE-main/Python FSE/Deepskilling/Module2_FrontendDev/FrontEnd Hands-on/handson_07/src/app/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  @Input() siteName: string = 'Student Portal';
}

<header class="site-header">
    <div class="logo">
        <a routerLink="/" style="text-decoration: none; color: white;">
            <span>{{ siteName }}</span>
        </a>
    </div>
    <nav class="nav-menu">
        <ul>
            <li><a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Courses</a></li>
            <li><a routerLink="/profile" routerLinkActive="active">Profile</a></li>
        </ul>
    </nav>
</header>

// Digital-Nurture-PythonFSE-main/Digital-Nurture-PythonFSE-main/Python FSE/Deepskilling/Module2_FrontendDev/FrontEnd Hands-on/handson_05/src/components/Header.jsx
import React from 'react';

export default function Header({ siteName, enrolledCount }) {
    return (
        <header className="site-header">
            <div className="logo">
                <span>{siteName}</span>
            </div>
            <nav className="nav-menu">
                <ul>
                    <li><a href="#courses" className="active">Courses</a></li>
                    <li><a href="#profile">Profile</a></li>
                </ul>
            </nav>
            <div className="enrollment-badge">
                Enrolled Courses: <span className="badge-count">{enrolledCount}</span>
            </div>
        </header>
    );
}
