// Digital-Nurture-PythonFSE-main/Digital-Nurture-PythonFSE-main/Python FSE/Deepskilling/Module2_FrontendDev/FrontEnd Hands-on/handson_07/src/app/student-profile/student-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-student-profile',
  templateUrl: './student-profile.component.html',
  styleUrls: ['./student-profile.component.css']
})
export class StudentProfileComponent implements OnInit {
  profileForm!: FormGroup;
  submittedData: any = null;

  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {
    this.profileForm = this.fb.group({
      name: ['', [Validators.required]],
      email: ['', [Validators.required, Validators.email]],
      semester: ['', [Validators.required, Validators.min(1), Validators.max(8)]]
    });
  }

  onSubmit(): void {
    if (this.profileForm.valid) {
      console.log('Form Submitted!', this.profileForm.value);
      this.submittedData = this.profileForm.value;
      alert(`Profile Saved Successfully:\nName: ${this.submittedData.name}\nEmail: ${this.submittedData.email}\nSemester: ${this.submittedData.semester}`);
    }
  }

  // Helper getters for validation display
  get nameControl() {
    return this.profileForm.get('name');
  }

  get emailControl() {
    return this.profileForm.get('email');
  }

  get semesterControl() {
    return this.profileForm.get('semester');
  }
}

<div class="profile-section">
    <h3>Student Profile (Reactive Form)</h3>
    
    <form [formGroup]="profileForm" (ngSubmit)="onSubmit()" class="profile-form">
        <!-- Name Field -->
        <div class="form-group">
            <label htmlFor="name-input">Full Name</label>
            <input 
                type="text" 
                id="name-input" 
                formControlName="name"
                class="form-control"
                [class.invalid-field]="nameControl?.touched && nameControl?.invalid"
            />
            <div class="error-msg" *ngIf="nameControl?.touched && nameControl?.errors?.['required']">
                Name is required
            </div>
        </div>

        <!-- Email Field -->
        <div class="form-group">
            <label htmlFor="email-input">Email Address</label>
            <input 
                type="email" 
                id="email-input" 
                formControlName="email"
                class="form-control"
                [class.invalid-field]="emailControl?.touched && emailControl?.invalid"
            />
            <div class="error-msg" *ngIf="emailControl?.touched && emailControl?.invalid">
                <span *ngIf="emailControl?.errors?.['required']">Email is required</span>
                <span *ngIf="emailControl?.errors?.['email']">Enter a valid email</span>
            </div>
        </div>

        <!-- Semester Field -->
        <div class="form-group">
            <label htmlFor="semester-input">Current Semester</label>
            <input 
                type="number" 
                id="semester-input" 
                formControlName="semester"
                class="form-control"
                [class.invalid-field]="semesterControl?.touched && semesterControl?.invalid"
            />
            <div class="error-msg" *ngIf="semesterControl?.touched && semesterControl?.invalid">
                <span *ngIf="semesterControl?.errors?.['required']">Semester is required</span>
                <span *ngIf="semesterControl?.errors?.['min'] || semesterControl?.errors?.['max']">
                    Semester must be between 1 and 8
                </span>
            </div>
        </div>

        <!-- Submit Button -->
        <button 
            type="submit" 
            class="save-btn" 
            [disabled]="profileForm.invalid"
        >
            Update Profile
        </button>
    </form>

    <div class="profile-preview" *ngIf="submittedData">
        <h4>Last Submitted Data</h4>
        <p><strong>Name:</strong> {{ submittedData.name }}</p>
        <p><strong>Email:</strong> {{ submittedData.email }}</p>
        <p><strong>Semester:</strong> Semester {{ submittedData.semester }}</p>
    </div>
</div>

// Digital-Nurture-PythonFSE-main/Digital-Nurture-PythonFSE-main/Python FSE/Deepskilling/Module2_FrontendDev/FrontEnd Hands-on/handson_05/src/components/StudentProfile.jsx
import React, { useState } from 'react';

export default function StudentProfile() {
    const [profile, setProfile] = useState({
        name: 'Jane Doe',
        email: 'jane.doe@university.edu',
        semester: '6'
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setProfile(prev => ({
            ...prev,
            [name]: value
        }));
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        alert(`Profile Saved Successfully:\nName: ${profile.name}\nEmail: ${profile.email}\nSemester: ${profile.semester}`);
    };

    return (
        <div className="profile-section">
            <h3>Student Profile</h3>
            <form onSubmit={handleSubmit} className="profile-form">
                <div className="form-group">
                    <label htmlFor="profile-name">Full Name</label>
                    <input 
                        type="text" 
                        id="profile-name" 
                        name="name" 
                        value={profile.name} 
                        onChange={handleChange} 
                        required 
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="profile-email">Email Address</label>
                    <input 
                        type="email" 
                        id="profile-email" 
                        name="email" 
                        value={profile.email} 
                        onChange={handleChange} 
                        required 
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="profile-semester">Current Semester</label>
                    <input 
                        type="number" 
                        id="profile-semester" 
                        name="semester" 
                        min="1" 
                        max="8" 
                        value={profile.semester} 
                        onChange={handleChange} 
                        required 
                    />
                </div>
                <button type="submit" className="save-btn">Update Profile</button>
            </form>

            <div className="profile-preview">
                <h4>Live Preview</h4>
                <p><strong>Name:</strong> {profile.name}</p>
                <p><strong>Email:</strong> {profile.email}</p>
                <p><strong>Semester:</strong> Semester {profile.semester}</p>
            </div>
        </div>
    );
}
